### ISSUE TITLE
和原有的页面窗口重叠

### ISSUE THREAD

**Issue by chengkai7300** [gaogaotiantian/biliscope#1]
部分页面会出现B站的个人信息卡片和这个插件产生的卡片重叠的情况：
1）在动态页面，点开视频下方的评论区
<img width="542" alt="截屏2023-03-10 18 55 00" src="https://user-images.githubusercontent.com/48372811/224299661-7b50a451-28da-4939-9159-eab83574b082.png">

2）视频详情页，up主的链接上
<img width="713" alt="截屏2023-03-10 19 54 02" src="https://user-images.githubusercontent.com/48372811/224310635-4ef3f737-b86e-47c3-a978-123de4b8aa3b.png">

**Comment by gaogaotiantian** [comment]
Fixed in 0.1.4
