### ISSUE TITLE
不兼容Dark Reader

### ISSUE THREAD

**Issue by Ybr2007** [gaogaotiantian/biliscope#10]
对于Dark Reader插件，不能使卡片的样式与深色模式兼容
如图：
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/79822594/224493117-0f99ec0e-7b61-4992-8c9f-b6ac92cadf88.png">

**Comment by gaogaotiantian** [comment]
没有第三方插件支持第三方插件的道理呀。不然的话，是不是应该考虑给dark reader提个issue支持其他插件呢……在某个第三方插件不是绝对主流的情况下，肯定不会写额外的代码去支持的，因为我们都是第三方……

**Comment by Ybr2007** [comment]
哦，明白了，谢谢

**Comment by trytodupe** [comment]
那可不可以考虑一下独立于这个dark reader，直接添加深色模式的css和设置？
