### ISSUE TITLE
[Bug] edge 中搜索标签时无法加载头像

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#103]
### 问题描述
![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/60ee0ebc-f2b8-4c10-89fa-694918c7e9ae)

### 解决方法
看了下正常加载头像的源码，图片后缀为 `.webp`
![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/f3f23826-076b-4a19-958c-6ed3cdec7df9)

而当前的源码，为 `.avif`
https://github.com/gaogaotiantian/biliscope/blob/4d62ca32486bea4fc6c5511cb501155e4a609898/scripts/searchpage.js#L11-L13

疑似b站更换图片格式导致问题

**Comment by gaogaotiantian** [comment]
edge本身好像对avif的支持有问题，所以b站在edge上显示的是webp。我试了一下chrome上是支持webp的，所以就直接用webp也ok。
