### ISSUE TITLE
[FR] 悬停在视频上显示当前视频的视频AI总结

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#106]
### 新需求背景
B站web端增加了[获取AI总结内容](https://socialsisteryi.github.io/bilibili-API-collect/docs/video/summary.html)（测试版），感觉可以加入至 `biliscope` 中。

### 新功能操作方式
悬停在视频上按下某个键将显示当前视频的视频AI总结（固定显示在标题下方）

### 实现难度
可能需要一个新的卡片UI用来专门显示

**Comment by gaogaotiantian** [comment]
不要总想一些奇怪的互动方式……尽量少增加新的操作。现在的卡片是悬停在用户名上的，这个feature如果出现只需要悬停在视频上就好了。

但是更重要的是，现在有多少视频支持这个功能。

**Comment by F-park** [comment]
> 不要总想一些奇怪的互动方式……尽量少增加新的操作。现在的卡片是悬停在用户名上的，这个feature如果出现只需要悬停在视频上就好了。
> 
> 但是更重要的是，现在有多少视频支持这个功能。

确实不应该增加新的操作，但悬停在视频上就显示 “视频AI总结” 会导致很容易误触吧（视频封面占据的区域还挺大的，可能会导致 api 访问太过频繁），我觉得还是需要一个按键来触发。（但不应该是鼠标中键，我试了一下按下这个键会在新标签页打开这个视频）

---

我看了一下我 web 端主页推荐的视频，好几个几千播放的视频都有视频AI总结（有人声音频就会产生AI总结），具体有多少视频支持要交给 python 脚本来验证。

**Comment by gaogaotiantian** [comment]
悬停在视频上显示总结和悬停在up主名字上显示卡片是一样的啊，由于debounce的存在，鼠标不是经过视频就会触发这个卡片，需要在上面停留一定的时间才会触发，现在卡片也是这样的，你的鼠标滑过up主名字的时候什么都不会发生。

**Comment by F-park** [comment]
> 悬停在视频上显示总结和悬停在up主名字上显示卡片是一样的啊，由于debounce的存在，鼠标不是经过视频就会触发这个卡片，需要在上面停留一定的时间才会触发，现在卡片也是这样的，你的鼠标滑过up主名字的时候什么都不会发生。

如果有一定响应延迟的话那看起来可以增加这个特性，应该能很好的提升用户体验。
