### ISSUE TITLE
[FR] 增加显示“共同关注"的人数

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#107]
### 新需求背景
可以使用 cookie 来查询用户与 up 主的[共同关注](https://socialsisteryi.github.io/bilibili-API-collect/docs/user/relation.html#%E6%9F%A5%E8%AF%A2%E5%85%B1%E5%90%8C%E5%85%B3%E6%B3%A8%E6%98%8E%E7%BB%86)

### 新功能细节
可以显示在平均稿件长度的左边或右边，格式：`共同关注 8/10 `（互关人数/该up的总关注数）。

**Comment by gaogaotiantian** [comment]
这是一个信息量非常少的功能。因为up主的信息核心是up的“输出属性”，而不是up的“喜好”。当你去用这个信息判断一个up是不是值得看，或者值得关注的时候，你需要获取的是他发的视频相关的信息，而不是他爱看谁。这和在社交媒体上交朋友有着很大的区别（你可以通过他喜欢什么来判断要不要和他玩）。

**Comment by F-park** [comment]
> 这是一个信息量非常少的功能。因为up主的信息核心是up的“输出属性”，而不是up的“喜好”。当你去用这个信息判断一个up是不是值得看，或者值得关注的时候，你需要获取的是他发的视频相关的信息，而不是他爱看谁。这和在社交媒体上交朋友有着很大的区别（你可以通过他喜欢什么来判断要不要和他玩）。

其实我一开始的想法是用来鉴定营销号和判断这个账号是否是有人在经营（有的账号只是多平台同时发布），并不是单纯看字面意义的“共同关注”。但事实确实和你说的一样，有效信息太少了，而且互相关注看的是喜好上的关系，不是视频想表达的内容，所以什么都看不出来。

我还研究了一下，如果目标 up 主不给看他的关注，这个接口会返回"用户已设置隐私，无法查看"，所以这个接口很大概率获取不到信息。
