### ISSUE TITLE
[FR] 移除词云中的 aid, bvid 和年份

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#112]
![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/a8bc9ba6-7bdb-4281-902a-a36bf8d2c996)
### 移除原因
我觉得 aid 和 bvid 是无效信息，因为词云不能复制，只能知道这个 up 视频简介中经常有这个视频，但无法知道具体内容。
年份的话也看不出来什么，我觉得可以排除2000-2024，防止排除到直播房间号。

**Comment by gaogaotiantian** [comment]
bvid这边如果有个regex是可以。时间的话我觉得是有效信息，虽然不一定是价值极高的信息。有大量的这种信息可能表示这个up喜欢做盘点啥的
