### ISSUE TITLE
信息框的大小如果被挡住的话只会在鼠标移动的时候才更新位置

### ISSUE THREAD

**Issue by winliyou** [gaogaotiantian/biliscope#12]
可以改成词云加载完毕后更新一下

**Comment by gaogaotiantian** [comment]
你的版本是0.1.4么？在0.1.4的时候修复了一下一个相关问题。如果是的话，可以截个图么。

**Comment by winliyou** [comment]
是0.1.4，我 clone 的代码，用的最新的的
![截屏2023-03-13 19 33 55](https://user-images.githubusercontent.com/127672431/224690932-4ff00ab5-d211-4640-ae0c-7a2bc5f48c65.png)
![截屏2023-03-13 19 35 01](https://user-images.githubusercontent.com/127672431/224690976-80c4fc07-daac-499a-9589-862e693d123d.png)
<img width="634" alt="截屏2023-03-13 19 37 01" src="https://user-images.githubusercontent.com/127672431/224691136-442b0a5a-803c-40b5-8883-87457759b606.png">

**Comment by gaogaotiantian** [comment]
应该是 #7 引入的动画导致的，我加了一个trainsitionend的trigger，解决了这个问题。
