### ISSUE TITLE
[FR] 为视频AI总结添加快捷键支持

### ISSUE THREAD

**Issue by XMB-7** [gaogaotiantian/biliscope#133]
目前鼠标悬浮将会自动触发”视频AI总结“浮窗, 这在主页上是挺好用的, 但当滚动鼠标往下查看动态的列表时, 就比较添乱了, 彼时将会非预期地弹出各视频的内容总结, 影响对动态列表的正常查看.
<img src="https://github.com/gaogaotiantian/biliscope/assets/65625632/2b5e6590-5bf1-40cd-bbbb-a4d83cd4f78c" width="300">

---

建议为之添加自定义快捷键, 以禁止自动触发, 使之转为主动调用, 比如ctrl+悬浮, 或者alt+b之类的.

**Comment by F-park** [comment]
去动态界面看就好了，不然还会遇到#96 的问题，目前还无法解决。

**Comment by F-park** [comment]
> 非预期地弹出各视频的内容总结

这确实是个问题，可能需要加个属性，把这里的触发时间设置长一点。

**Comment by F-park** [comment]
> 非预期地弹出各视频的内容总结

这确实是个问题，可能需要加个属性，把这里的触发时间设置长一点。

**Comment by gaogaotiantian** [comment]
这里的问题是每个人的“预期”是不一样的。在任何一个视频链接都弹出总结，不一定符合所有人的“预期”，但是是一个统一的behavior。默认触发改成主动是不可能的，但是增添一个主动触发的选项是可以的。就是默认是自动，可以改成完全不触发，或者按键主动触发。

在不同的页面有完全可自定义的行为这个事情的维护压力偏大了，我个人可能倾向于不这么干。

**Comment by XMB-7** [comment]
> 在任何一个视频链接都弹出总结，不一定符合所有人的“预期”，但是是一个统一的behavior。在不同的页面有完全可自定义的行为这个事情的维护压力偏大了，我个人可能倾向于不这么干。

呃, 我只是想把该功能的触发方式从a改成b, 行为仍然是统一的, 而并不想同时在某些页面用a方式触发完了在另一些页面想用b方式触发.

> 默认触发改成主动是不可能的，但是增添一个主动触发的选项是可以的。就是默认是自动，可以改成完全不触发，或者按键主动触发。

如果给该弹出ai总结浮窗功能添加了按键支持, 那用户只要不自定义快捷键, 自然就是维持默认的鼠标悬浮自动触发, 而如果用户自定义了快捷键, 自然就从自动触发转为主动触发了. 
楼上提到了#96, 估计改为按键触发可能存在一些技术上的难点. 但最笨的想法是, 鼠标悬浮之后一直等待接收指定按键, 等到了才触发弹窗, 等不到就一直等. 或者简单粗暴一点, 允许用户自行增加鼠标悬浮触发弹窗的触发时间, 也都很有帮助.

**Comment by F-park** [comment]
> 允许用户自行增加鼠标悬浮触发弹窗的触发时间


我觉得这个方案可行，相当于灵敏度设置，不想太容易触发就把触发时间设置长一点
