### ISSUE TITLE
[FR] 增加评论历史记录和弹幕历史记录

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#135]
## 新需求背景

有时候发送过的评论/弹幕可以复用/参考。

如果增加评论/弹幕历史卡片，就能找回这些内容。

### 卡片显示位置

评论直接内嵌显示，弹幕用弹窗来显示。（显示在红框以及下面的位置，当焦点在评论框才显示）
![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/c885d0a7-f503-4bc3-a37e-58cc8e9f140e)
![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/a7dbd4b2-2fec-41b7-9512-d4d3912103af)

### 新卡片细节

- 评论和弹幕的历史数据分开来存
- 顶部增加搜索框，可以搜索历史
- 默认显示六条（这里可自定义），溢出显示滚动条
- 可以把历史设为置顶，相当于常用语（在弹幕中估计会很实用）
- 可自定义短于多少字数/只含表情/只含@的历史不记录

**Comment by gaogaotiantian** [comment]
这里存在若干个问题，我们分开说。

首先，是一个方向上的问题。因为我们的精力还是有限的，所以BiliScope的大方向，是读。也就是让用户可以更了解B站的内容，获取更多的信息。BiliScope是来自于Microscope，图标也是个显微镜。就是我们做的大方向，一定是看得更细。当然，如果有一些有趣的功能，也不是不能做，只是说大方向上还是要尽量维护。

其次，对于这个功能，你怎么获取“历史”呢？是biliscope自己去hook一个函数么？还是调用API？我甚至不确定有没有“我曾经发过的弹幕”这种API。自己hook函数的话不是一个小的工作量。

对于chrome extension，它的存储有两部分，第一个是sync的，可以在浏览器之间互通的，这个我们拿来保存一些选项，但是很小，就100k。还有一个是local的，5M，现在是用来存notes的。保存数据是要花空间的，而chrome extension给我们的空间并不多。所以一切需要花空间的功能，都要三思。那你这个历史，要么就是保存到extension，要么就是每次开浏览器去读一遍，无论哪种方式，cost都非常大吧？

然后关于功能。弹幕我还可以理解，你发评论也经常会发一样的么？我觉得一个正常人，对不同视频的评论肯定是相差很大的啊。弹幕有个常用的我觉得合理一些。

因此，对于这个feature，即便是做，我觉得更合理的方式是——在选项中可以设置几个“常用弹幕”，我们只保存这几个。如果设置了，在对应的地方显示，点一下可以复制到弹幕输入框。也就是默认情况下是不打扰用户的，需要用户opt-in。

**Comment by F-park** [comment]
这两个功能看起来实用性太低了，close 了
