### ISSUE TITLE
[FR] 增加收藏评论的功能

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#136]
## 新需求背景

灵感来自标星 github gist（代码片段）

评论如果是创作的点子或者启发了思考，就能收藏起来，要用到的时候再搜索出来看。

### 评论区

鼠标移到某条评论的区域时，才在该评论的红框区域显示一个星星的 icon。

![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/fc3a1e9c-01de-4d9d-ac61-a98e6a14fd4e)

类似评论右边的菜单选项，只能最多显示一个。而且当鼠标移到该条评论的区域时才显示

![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/8d522c54-9620-410f-bc09-a987eb18c1d9)

### 收藏

- B站右上角收藏的弹窗中，在“稍后再看”下面的位置增加“评论收藏夹”
- 个人空间的收藏中，在“默认收藏夹”下面的位置增加“评论收藏夹”

![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/bd923184-11d7-4577-bf38-b6c876098714)
![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/11452e2b-1f1b-416a-b8d5-599060915d3f)

### 搜索

-  `> ` （makedown 语法，需要一个空格）
- `评论：` （纯中文语法，中文冒号）

当搜索关键词以上面的关键词开头时，自动跳转到个人空间的收藏页面，并进行搜索。

**Comment by gaogaotiantian** [comment]
这个问题和另外一个issue几乎是完全一样的。首先，它是一个输入性的feature。其次，它要空间。另外说实话我觉得这个feature的需求还不如常用弹幕多，而且实现起来是有复杂度的，侵入性也更强一些。

这我觉得属于幻想出来的需求，起码这个阶段完全没必要做。
