### ISSUE TITLE
支持在视频详情页/个人空间中也展示词云

### ISSUE THREAD

**Issue by cocolato** [gaogaotiantian/biliscope#14]
目前在视频详情和个人空间页面的话，貌似没有展示词云的入口。

感觉平时在首页/热门页都是先被一个视频吸引，不会一上来就注意到up主，然后看完视频后再对这个up主感兴趣，如果这两个界面能加一个词云，会对了解up主更有帮助。

![image](https://user-images.githubusercontent.com/35182391/224878587-9b397988-106b-440b-9a31-af5ab88d45f1.png)

**Comment by cocolato** [comment]
插件版本0.1.4,不知道是不是0.1.5中已经更新了

**Comment by gaogaotiantian** [comment]
之前的逻辑是，对于所有已经有card的情况，都避免显示。在0.1.5版本里，开始替代了一些原有的card，主要是在space和topic里。视频界面的up目前还没有替代。

**Comment by fish1968** [comment]
插件在[多作者视频页](https://www.bilibili.com/video/BV1nf4y177Yj) 会错误的 同时显示 原有 card 和 插件 card

**Comment by gaogaotiantian** [comment]
是的，因为是直接查的target link，个人空间里首页和动态的target link和在主页上的up link是一致的，所以都会显示。

**Comment by gaogaotiantian** [comment]
现在都显示了，把这个issue关了。
