### ISSUE TITLE
关注后不会切换关注状态

### ISSUE THREAD

**Issue by GoldenTotem** [gaogaotiantian/biliscope#144]
点击up卡片上的关注按钮后，头像下方的蓝色关注条没有变为灰色已关注，需要刷新网页才生效。

**Comment by gaogaotiantian** [comment]
Biliscope不会去轻易动态更改网页上的信息，因为非常难全部track到。不同的页面都有不同的方式显示一个up是不是被你关注了，想把每个页面都改动工作量偏大，而且意义偏小。带来的维护成本也是过高了。

现在Biliscope只保证在点了up卡片上的关注按钮之后，up卡片上的关注按钮会变化，也就是在卡片上能看出来你关注了他。
