### ISSUE TITLE
BUG: 有些视频无法显示AI总结（插件无法实现，但B站自带的按扭可以）

### ISSUE THREAD

**Issue by MicReed** [gaogaotiantian/biliscope#145]
有些视频无法显示AI总结。
比如搜索：“ai视频总结”， 然后悬停在你宣传biliscope的视频上，显示“此视屏不存在AI总结”，但是点开后，可以用网业端自带的Ai视频总结按钮显示。
![image](https://github.com/gaogaotiantian/biliscope/assets/60501042/e13f340e-3505-4316-94b5-1172dfd4256f)
![image](https://github.com/gaogaotiantian/biliscope/assets/60501042/d70441d3-5011-4cb4-a5e2-2e3ea9c3471c)

**Comment by gaogaotiantian** [comment]
这是B站自己内部的API没有统一好，因为biliscope是直接调用的API，如果API返回是没有那只能显示没有，就在我们这边没有任何办法。

**Comment by F-park** [comment]
这其实就是 bug，我们代码的逻辑是只要没摘要就不显示。但此时摘要没有内容，大纲有内容，下面这个视频也可以复现。
https://space.bilibili.com/350884559/search/video?keyword=%E9%BB%91%E7%A5%9E%E8%AF%9D%E5%8F%A4%E5%BB%BA%E7%AD%91%E6%89%AB%E6%8F%8F%E7%A7%91%E6%99%AE%EF%BC%9A%E5%AE%9E%E6%99%AF%E6%89%AB%E6%8F%8F%E6%98%AF%E5%81%B7%E6%87%92%E7%85%A7%E6%90%AC%EF%BC%9F%E8%A6%81%E6%88%91%E8%AF%B4%EF%BC%8C%E6%94%BE%E5%B1%81%EF%BC%81
