### ISSUE TITLE
[BUG] 置顶评论中含有 av 号的 jump_url 时，会被标识为广告。

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#155]
## 问题代码

https://github.com/gaogaotiantian/biliscope/blob/d237fc5aebe385e81a7d6f0afbcd77442b5ac9a6/scripts/videotag.js#L42-L49

## 问题描述

此时的 `key` 会为 `av` + 一串数字，例：`av2333`

**Comment by gaogaotiantian** [comment]
有没有视频的例子发一下我看看~

**Comment by F-park** [comment]
https://www.bilibili.com/video/BV1Ps411G7ss/
