### ISSUE TITLE
能不能有更新日志，现在哪个版本更新了什么我都不知道，还是自动更新的，都不知道啥时候更新的蹦出来新内容

### ISSUE THREAD

**Issue by zerobiubiu** [gaogaotiantian/biliscope#157]

**Comment by gaogaotiantian** [comment]
Hmm，如果现在需要的话可以看github上的release，每个release会写。Chrome extension有在主页放更新日志的习惯么……

**Comment by zerobiubiu** [comment]
还真没注意过哪里，你的冲浪强度好高啊，这么快就回复了

**Comment by gaogaotiantian** [comment]
因为email有提示……

**Comment by zerobiubiu** [comment]
我以为你这么忙会在有时间的时候才会回复

**Comment by gaogaotiantian** [comment]
现在是晚上11点半，是我最有时间的时候了。这个issue我先关了，自动更新这个事情确实是extension特点，当然你是可以关掉的。然后更新日志如果真的需求，github这个release可以看。其他的地方我也没找到很合适的位置，然后好像大部分extension也不太写。

**Comment by zydou** [comment]
请问如何关闭自动更新日志，这个功能非常恼人

**Comment by zydou** [comment]
想知道更新什么内容完全可以订阅repo，会有通知的

**Comment by gaogaotiantian** [comment]
下一个版本会加一个选项关闭显示自动更新，并且会在自动更新的页面提示这个选项。
