### ISSUE TITLE
[Bug] 含B站短链的广告无法识别

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#161]
### 复现样例

https://www.bilibili.com/video/BV1GE421P78T

### 问题代码

https://github.com/gaogaotiantian/biliscope/blob/d0af2507ca04421fa828d24234f20ef0413d7bc5/scripts/videotag.js#L42-L51

此时 key 和 value 的值

![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/20935691-e9a5-40a8-99ee-0fb44f184075)

这里的广告使用的是B站短链，被认为是内部引用跳过了。

**Comment by F-park** [comment]
### 另一个案例
https://www.bilibili.com/video/BV1HT421k7yM/
![image](https://github.com/gaogaotiantian/biliscope/assets/52167622/a40c83f3-c35a-4cf3-8a68-01dbd4ea4da4)
b站花火平台的短链广告，同样的原因。

**Comment by gaogaotiantian** [comment]
这里我逻辑写错了，是下面那个`goods_cm_control`的问题，我整体调整一下，那里有毛病。
