### ISSUE TITLE
[Enhancement] 设置中的保存按钮需要滚动才能看到

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#174]
在 Edge 中，目前设置中的保存按钮刚好在页面外，需要滚动才能看到。

![image](https://github.com/user-attachments/assets/ec0a8ab9-991c-486c-8927-de95e3ceb139)

对于 biliscope 的新用户，可能会让他们无法保存设置。可能需要将设置项做成列表形式？

**Comment by gaogaotiantian** [comment]
确实需要稍微整理一下这里了，我来给它调整一下。
