### ISSUE TITLE
[FR] 视频卡片显示热评

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#177]
## 灵感来源

网页端动态热评/移动端搜索视频附带的热评/评论区中的热评标签

![image](https://github.com/user-attachments/assets/527fa6d7-4582-4591-b8ac-98f164a2abe9)

![IMG_20240721_220927.jpg](https://github.com/user-attachments/assets/b0c10df8-440c-4cdd-9c89-dc01e736af00)

## 热评规律

- 没找到获取单个视频热评的API，疑似后端合成后返回
`https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space`

- 有热评  ![image](https://github.com/user-attachments/assets/5938c811-a56b-4279-b606-4ac96bae3cc4) 标签的（可能同时存在两个热评）
`https://api.bilibili.com/x/v2/reply/wbi/main`
`data.replies[].attr` == 32768

- 经观察，网页端动态会选高赞且只有一行的评论为热评

- 移动端优先显示最高赞为热评（忽略热评标签的评论）

**Comment by F-park** [comment]
我偏向热评标签优先，其次最高赞的评论为热评。
如果要做这个功能的话，或许能通过缩减 AI 总结的高度，来塞下热评。

**Comment by gaogaotiantian** [comment]
热评可以放，但是你需要prototype一下怎么放好看。

但是这里要看你要做多少个API call。我最多最多可以接受触发视频总结之后多一个extra call，再多benefit就不到cost了。
