### ISSUE TITLE
[FR] 将赞助商标记为 `广告`

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#183]
## 需求来源

当合作视频中的成员为赞助商，可以确定视频为商单。
![image](https://github.com/user-attachments/assets/9a27fb64-5bd3-4204-af78-fb2221a93847)

**Comment by gaogaotiantian** [comment]
商单和广告是一个意思，在我做广告tag的时候，意思就是商单。这个feature是ok的，但是没必要加个新tag，还是写广告就行。

如果你想做可以做，如果你不想做这几天我可以做一下。
