### ISSUE TITLE
[Bug] 两个 `updateVideoInfo` 函数进行了两次网络请求，没读取到 cache

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#187]
## 请求图

![image](https://github.com/user-attachments/assets/102887ad-a75e-49cc-a089-03c1590aca1d)

## 问题原因

网络请求没正常逻辑快，导致 `cacheAndUpdateVideo` 函数没 cache 上
https://github.com/gaogaotiantian/biliscope/blob/1358358dac8872900f5f00b9476411e9f7e25305/scripts/biliscope.js#L42-L63

**Comment by HankBO** [comment]
也许可以给fetch前加一个await？
https://github.com/gaogaotiantian/biliscope/blob/1358358dac8872900f5f00b9476411e9f7e25305/scripts/biliapi.js#L47

**Comment by gaogaotiantian** [comment]
你的操作是什么？快速触发了两次同一个video的card？这不是一个critical issue，没啥大问题的。

**Comment by F-park** [comment]
就是正常悬停视频，在我的 edge 浏览器几率 100% 复现这个问题。
