### ISSUE TITLE
弹出的卡片在某些情况下会卡住（一直在一个相对位置跟随鼠标移动，不会消失）

### ISSUE THREAD

**Issue by NekoisJelly** [gaogaotiantian/biliscope#19]
但是还没有猜到稳定复现的步骤=。=

印象中大概的操作步骤：
1.动态界面的评论区点击了一个@UP的链接跳转到UP主页
2.在打开的UP主页点击了个视频
3.看完之后关闭视频页、UP主页，回到动态页
4.发现卡片一直跟随鼠标移动不消失

环境：
win11+edge浏览器

**Comment by TangbohuDianPaoZhang** [comment]
看看我的这个issue，你能不能用我的方法复现这个bug
#21

**Comment by gaogaotiantian** [comment]
在 853cff09f59cec689c20010cc9d14b082a529716 中尝试修复了这个问题，应该是好了。
