### ISSUE TITLE
弹出页面显示不完整

### ISSUE THREAD

**Issue by devycx** [gaogaotiantian/biliscope#2]
![Animation](https://user-images.githubusercontent.com/100667021/224465203-76e7f505-cb15-4b86-bd87-1bb47ea2db75.gif)

**Comment by gaogaotiantian** [comment]
你这个是完整的浏览器么？你下面也没有空间了啊。。能截图截一个完整的浏览器么？

**Comment by NekoisJelly** [comment]
因为鼠标那个位置下边的空间不够显示完整的弹窗了，所以就挪到上面去了=。=

**Comment by devycx** [comment]
说得对，下边空间刚好差几个像素无法显示，导致去上面显示的
