### ISSUE TITLE
[FR] 增加视频标签 `AI`

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#202]
## 条件

当视频出现下面的争议提示时
![image](https://github.com/user-attachments/assets/86e3c84f-9707-42cb-bb46-40a53093dcb6)

## 数据

`https://api.bilibili.com/x/web-interface/wbi/view`  中的
`data.argue_info.argue_msg == "该内容疑似使用AI技术合成，请谨慎甄别"`

## 例子

https://www.bilibili.com/video/BV1A1hheaEKk/

**Comment by gaogaotiantian** [comment]
这个数据现在出现的多么？我在想，既然它是个message的形式，那未来可能还有不少这种message吧？都以tag的形式展示么？

**Comment by F-park** [comment]
这个 message 是被b站识别出来自动加的，基本只在鬼畜区的某几个分区出现，也有在发布视频时自选的 message。也许可以放到视频卡片上?

**Comment by gaogaotiantian** [comment]
这个东西放视频卡片当然是ok的。但是我是觉得，如果它目前很少出现，我们可以暂时不管这个东西。等以后它相对来说用处变大了再加。我们现在的用户体量，这种只在非常少的视频中出现的信息，感觉加上意义偏小。
