### ISSUE TITLE
弹出卡片不消失一直跟随鼠标移动

### ISSUE THREAD

**Issue by TangbohuDianPaoZhang** [gaogaotiantian/biliscope#21]
操作步骤：
1.在视频页选择一个视频点击
2.在网页没有加载完成时将鼠标指针指到任意up主的名字
3.触发bug，即使鼠标指针已经离开up主名字卡片依然不会消失

![image](https://user-images.githubusercontent.com/93420604/226173688-7f9762e9-b553-4135-bf92-e93a1fced3d0.png)

经过我的尝试，这个bug可以稳定复现

**Comment by NekoisJelly** [comment]
=。=我并没能复现……不过看描述是跟我那个一样的表现

**Comment by gaogaotiantian** [comment]
在 853cff09f59cec689c20010cc9d14b082a529716 中尝试修复了这个问题。
