### ISSUE TITLE
[bug]开起首页换一换的前进后退，如果刷新出直播卡片会导致换一换整个功能失效

### ISSUE THREAD

**Issue by UnfiniSmile** [gaogaotiantian/biliscope#211]
刚开始是我以为是网络或者内存溢出结果发现是因为刷新出直播卡片导致换一换整个功能失效<img width="732" alt="image" src="https://github.com/user-attachments/assets/1d2bd175-8c96-4cd9-bb6a-ff4d6480c1dd">

**Comment by gaogaotiantian** [comment]
我遇到过几次这个问题，一直没能复现。这个不是刷出了直播，而是你正常换一换的所有card被删没了。这个直播是后面跟着的card。我不是很确定哪里出现了racing issue。@F-park有机会你看一下这个bug。

**Comment by F-park** [comment]
我没遇到过这个问题，也无法复现。我的首页前十个卡片不会出现赛事卡片，难道你用的是b站旧版首页？

**Comment by F-park** [comment]
@Natrium0521 这个换一换是你做的，有时间的话可以看一下这个 bug。

**Comment by Natrium0521** [comment]
我遇到过，但是复现不出来，定位不到😇

**Comment by gaogaotiantian** [comment]
这是个恶性bug，如果无法解决，这个feature就要被拿掉（或者default disable）

**Comment by UnfiniSmile** [comment]
> 我没遇到过这个问题，也无法复现。我的首页前十个卡片不会出现赛事卡片，难道你用的是b站旧版首页？


> 这是个恶性bug，如果无法解决，这个feature就要被拿掉（或者default disable）


> 我遇到过，但是复现不出来，定位不到😇

不只是赛事直播，而是只要刷新出直播卡片，换一换就会卡住，且我这里100%稳定触发

https://github.com/user-attachments/assets/5f31acab-fe9a-4ec9-ab3c-9cbd5c80c388

**Comment by F-park** [comment]
确实是恶性 bug 了。这个直播卡片一直在后面的，其实就是把你前面的卡片吞掉了，应该要默认禁用这个特性了

**Comment by UnfiniSmile** [comment]
当关闭首页换一换的前进后退关闭时，直播卡片位置会固定下来，不会刷新到前面去

**Comment by Natrium0521** [comment]
定位到了，广告的问题，前后刷出一样的广告就会触发，在修了

**Comment by UnfiniSmile** [comment]
当出现bug时，网页界面下滑刷新和蓝色刷新内容按钮依然生效，
![image](https://github.com/user-attachments/assets/8bfcb950-a502-498d-b9dd-a285c3140baf)
![image](https://github.com/user-attachments/assets/a1bcdcb9-3245-43c7-b1e8-e9c09d807a94)
蓝色刷新内容按钮无法使被卡住的直播卡片包括前面的卡片刷新
![image](https://github.com/user-attachments/assets/439e7c6e-409a-4cf0-bbc1-979ead2d6b4a)

网页界面下滑刷新有概率使被卡住的直播卡片前面的卡片刷新走
![image](https://github.com/user-attachments/assets/953f5282-e73e-441d-bcb7-68bd4a832483)

**Comment by UnfiniSmile** [comment]
> 定位到了，广告的问题，前后刷出一样的广告就会触发，在修了

真的只是广告的问题嘛？好吧看来我的猜测可能有点差错
