### ISSUE TITLE
希望总结窗口里面的热门评论可以增加一个选择的开关

### ISSUE THREAD

**Issue by ElevenPlus666** [gaogaotiantian/biliscope#215]
这个插件非常棒，希望总结窗口里面的热门评论可以增加一个选择的开关，热门评论让我本不宽裕的总结窗口雪上加霜😂

**Comment by gaogaotiantian** [comment]
哦，当时没注意这个feature的开关，是应该搞一个。@F-park有空的时候可以加一下~
