### ISSUE TITLE
Firefox(version:129.0.2 AMD64) biliscope(version:0.6.1) 视频评论区显示IP地址有误

### ISSUE THREAD

**Issue by kimi996z** [gaogaotiantian/biliscope#224]
详情见图片
![Uploading feedback_bili_plugin.png…]()

**Comment by winix365** [comment]
图片没上传成功，我再上传一次
![feedback_bili_plugin](https://github.com/user-attachments/assets/7e6570a6-a40b-45a0-90e4-33960c636a2d)

**Comment by winix365** [comment]
视频地址：https://www.bilibili.com/video/BV1FpHeekE7x/

**Comment by winix365** [comment]
现在IP又正常显示了。。。

**Comment by gaogaotiantian** [comment]
hmm，这个我还真不是非常确定具体可能是什么原因导致的……

**Comment by F-park** [comment]
这里的数据直接从评论的 __data 属性读取的，按理来说不会出错的吧。

**Comment by kimi996z** [comment]
我知道怎么复现了，当评论排序改变后，IP似乎不会跟着改变。
案例链接[(https://www.bilibili.com/video/BV1xEtpeTE85/?#reply242672609953)]
![Snipaste_2024-09-21_16-40-12](https://github.com/user-attachments/assets/3732ef84-61d6-4022-b832-6c7b4a1b7c4e)
![Snipaste_2024-09-21_16-41-11](https://github.com/user-attachments/assets/322f1ccf-a273-4e2e-947f-095d50df2ab2)

**Comment by F-park** [comment]
复现了。就是 `点击查看` 之后原先的 ip 不会跟着刷新

**Comment by gaogaotiantian** [comment]
> 复现了。就是 `点击查看` 之后原先的 ip 不会跟着刷新

哦，我们是不是虽然hook了observer，但是现在的代码是只要有ip就直接不管了。

**Comment by F-park** [comment]
重新试了一下，现在又不会出问题了，估计是b站改了这个`点击查看`的逻辑。

**Comment by F-park** [comment]
@kimi996z 你是否还能复现这一问题，你上面发的案例视频被删掉了。

**Comment by kimi996z** [comment]
谢谢，已经很久没发现异常了
