### ISSUE TITLE
稍后再看视频问题

### ISSUE THREAD

**Issue by guoinfinite** [gaogaotiantian/biliscope#226]
如果把一个视频加入稍候再看,评论区就不会显示ip地址,鼠标悬停在头像和名字上也不会弹出卡片
因为不太懂前端,自己修改了下labelip.js和load.js的内容,希望大佬能适配下

**Comment by F-park** [comment]
参考 #196，旧版评论区，应该不会支持了，除非有人愿意适配。

**Comment by gaogaotiantian** [comment]
对那个是旧版的评论区，应该不适配了，相对来说是一个很偏门的地方。
