### ISSUE TITLE
希望增加一个开关 低质和广告标签 的常驻功能

### ISSUE THREAD

**Issue by Rushbe2021** [gaogaotiantian/biliscope#228]
希望增加一个开关 低质和广告标签 的常驻功能，让搜索页和推荐以及主页都主动显示，而不用鼠标悬停上去来能看到
谢谢了！

**Comment by F-park** [comment]
我觉得默认显示视频标签价值不是很大，没必要做。

每个视频要进行两次请求才能显示视频标签，太频繁的请求会造成 api 风控。

低质标签其实也有局限性，部分攻略视频有时也会被误伤。广告标签并不代表视频质量差，只代表这是商单。所以不要太依赖标签，仅供参考。
