### ISSUE TITLE
支持，过滤，筛选，排序，关注列表

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [gaogaotiantian/biliscope#23]
如 https://greasyfork.org/zh-CN/scripts/428895-bilibili-%E5%85%B3%E6%B3%A8%E7%AE%A1%E7%90%86%E5%99%A8
(或者直接联动也行)

**Comment by gaogaotiantian** [comment]
不是这个软件的功能方向，这个软件不是要做一个全能的B站小助手，它只是帮助你了解up的情况而已。未来可能会有视频的具体信息之类的，但是没有打算做关注列表的整理这个方向。
