### ISSUE TITLE
动态页更新新版评论区（除空间动态）

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#233]
空间动态页没更新，下面两种页面更新了。

https://t.bilibili.com/
https://www.bilibili.com/opus/*

**Comment by gaogaotiantian** [comment]
这个是和ip有关的是吧。

**Comment by F-park** [comment]
就是变 shadowRoot 了，id 和 ip 都有，也许可以合在一起标记?

**Comment by gaogaotiantian** [comment]
id和ip我们是不是都分开在别的地方处理过，只要把这些界面加入我们处理的逻辑里就可以了吧。

id有个问题是它得触发卡片弹出。
