### ISSUE TITLE
希望增加的功能

### ISSUE THREAD

**Issue by AXiX-official** [gaogaotiantian/biliscope#237]
对于已经关注的UP能否在卡片中显示关注的时间

**Comment by F-park** [comment]
想了一下，`关注时间`不是一个有价值的信息吧。不知道你的需求是怎么样，想知道关注 up 的原因应该给 up 做备注吧。

**Comment by AXiX-official** [comment]
主要是前段时间突然想看看都是什么时候开始关注的，但是没什么简单直观的查看方法

**Comment by gaogaotiantian** [comment]
Added in #238
