### ISSUE TITLE
[Bug] 脚本弹窗收起时意外使b站弹窗收起

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#239]
## 复现步骤

1. 鼠标移向右上角历史按钮
2. 悬停一个视频显示视频卡片
3. 移到另一个视频使视频卡片关闭，b站的弹窗被意外关闭

## 代码位置

setLeaveEvent 函数 
进入视频卡片不收起b站卡片的功能也没有对这个按钮生效(其他几个可以)

**Comment by gaogaotiantian** [comment]
这个我知道，是B站那边的历史那个东西写的有点毛病。
