### ISSUE TITLE
显示卡片优化

### ISSUE THREAD

**Issue by CyanChanges** [gaogaotiantian/biliscope#24]
动态的卡片貌似不显示，稍微看了下貌似都有bili-avatar这个class
能不能同时判断如果有bili-avatar也 显示

**Comment by gaogaotiantian** [comment]
没听懂要表达什么。。如果是技术细节可以拉PR。。或者说的具体一点，这句有点没头没尾。。

**Comment by Chinese-Cyq20100313** [comment]
> 没听懂要表达什么。。如果是技术细节可以拉PR。。或者说的具体一点，这句有点没头没尾。。

就是如果这个是一个UP主的卡片，那么它的href肯定指向他的space地址，可以通过这个判断要不要显示卡片

**Comment by Chinese-Cyq20100313** [comment]
还有动态貌似不显示

**Comment by gaogaotiantian** [comment]
动态不显示是expected。第一是因为本身已经有官方的卡片了，第二是获取uid比较复杂，因为它不是用href处理的。

**Comment by gaogaotiantian** [comment]
动态的部分已经处理完了，现在都可以显示了。
