### ISSUE TITLE
动态里的新位置比以前遮挡啊

### ISSUE THREAD

**Issue by Cyiming** [gaogaotiantian/biliscope#243]
视频总结会遮挡下一个动态

![Clip_2024-10-10_19-37-18](https://github.com/user-attachments/assets/7d390d48-8d7b-4385-a324-044fc16a6760)

**Comment by F-park** [comment]
你移开鼠标让弹窗消失不就好了？感觉不是问题

**Comment by gaogaotiantian** [comment]
视频总结这个feature的基本概念是，你在关注当前这个视频。因为既然是弹窗，它必然会遮住一些其他的内容。这次的修改核心逻辑是让它尽量不要遮住和这个视频相关的内容。你不会有同时看这个动态的视频总结，以及下一个动态的需求对吧？你肯定是两个只看一个。

但是对于动态这个网页来说，它的左边是空的啊，是不是可以把这个总结扔到左边去？

**Comment by Cyiming** [comment]
> 你移开鼠标让弹窗消失不就好了？感觉不是问题

问题是 浏览动态时 每一个视频都要被上一个视频总结遮挡 目前只能尽量避免鼠标接触视频区域 但这在快速浏览动态中是很难避免的 导致小心翼翼

**Comment by gaogaotiantian** [comment]
你在浏览的时候，鼠标有放到视频区域的需求么？因为我的话，会把鼠标放到右边那里，只转滚轴。视频现在弹窗的debounce还挺大的，应该是接近一秒的悬停才会弹，这就是停了一小阵了。当然，对于动态这个页面来说，其实甩到左边是更合适的，我们会改一下这里。

**Comment by Cyiming** [comment]
> 你在浏览的时候，鼠标有放到视频区域的需求么？因为我的话，会把鼠标放到右边那里，只转滚轴。视频现在弹窗的debounce还挺大的，应该是接近一秒的悬停才会弹，这就是停了一小阵了。当然，对于动态这个页面来说，其实甩到左边是更合适的，我们会改一下这里。

对的 我看到感兴趣视频需要点击视频区域留作待看 然后浏览下个视频时会被上个总结遮挡

**Comment by F-park** [comment]
现在会显示成这样了，应该可以满足你的需求。
![image](https://github.com/user-attachments/assets/dc9cd1e0-fac6-4450-b84b-23048e3a7f8f)

**Comment by Cyiming** [comment]
> 现在会显示成这样了，应该可以满足你的需求。 ![image](https://private-user-images.githubusercontent.com/52167622/375655233-dc9cd1e0-fac6-4450-b84b-23048e3a7f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDYwMjIsIm5iZiI6MTcyODY0NTcyMiwicGF0aCI6Ii81MjE2NzYyMi8zNzU2NTUyMzMtZGM5Y2QxZTAtZmFjNi00NDUwLWI4NGItMjMwNDhlM2E3ZjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDExMjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OWYwOTY4Mzg0ZmY0M2M1YWYwZWQxNDNjOWM2ZTZjYjkzNDZmM2U5M2Q1MDljYWU0NDg0MDI4YzA2MzQ0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DJyNulDv8fDVAhmQCyFXsHv1VxsM_q1WbA4ariNdoeI)

可以 如果再往左一点把头像漏出来就更好了 其实右边空间也是够的 看用户习惯吧
![Clip_2024-10-11_19-25-45](https://github.com/user-attachments/assets/475019d3-171f-4c20-a033-d50d3105f435)
