### ISSUE TITLE
接口风控导致卡片无法正常显示

### ISSUE THREAD

**Issue by lowking** [gaogaotiantian/biliscope#248]
![image](https://github.com/user-attachments/assets/d3dc47eb-80de-4fc0-b999-fed2d65c0764)
我这里是info接口返回风控

**Comment by F-park** [comment]
按道理来说不会风控，其他脚本用info请求过多了？可以F12过滤一下看看打开一个页面会有多少次info请求？

**Comment by lowking** [comment]
我只看[热门](https://www.bilibili.com/v/popular/all/)，似乎从几天前开始就一直这样了，到今天还没恢复。
打开一次页面没有info请求，只有移到up主名字那会有，会不会是浏览的时候太频繁触发资料卡导致的？感觉可以加个资料卡弹出延迟，避免频繁弹出

**Comment by F-park** [comment]
up 主名字的范围很小吧，感觉不会出现误触的情况？目前需要悬停300毫秒才会弹出用户卡片。

**Comment by lowking** [comment]
那就不知道撒原因了，我都不会特意查看用户卡片，只有想拉黑人的时候才会用到

**Comment by gaogaotiantian** [comment]
你B站登录了么？

**Comment by AkagiYui** [comment]
我这边在相同的场景也出现了相同的状况。

**Comment by gaogaotiantian** [comment]
登录了么？

**Comment by AkagiYui** [comment]
登录了的。并且我在Chrome新建一个干净的“个人资料”，登录其他Bilibili账号重复此动作获得相同的结果。

查看[SocialSisterYi/bilibili-API-collect/issues/1107](https://github.com/SocialSisterYi/bilibili-API-collect/issues/1107)，可能有帮助。

**Comment by gaogaotiantian** [comment]
okay那就是B站那边额外加了一个风控，我们等几天看一下解决方案吧。

**Comment by lowking** [comment]
> okay那就是B站那边额外加了一个风控，我们等几天看一下解决方案吧。

![image](https://github.com/user-attachments/assets/85c70f6a-9808-4e17-9345-fd301286832c)
又一次出现了
