### ISSUE TITLE
已注销账号卡片显示错误

### ISSUE THREAD

**Issue by noonisy** [gaogaotiantian/biliscope#254]
![p1](https://github.com/user-attachments/assets/da52e404-6a09-4939-b21a-9988d97a7871)
![p2](https://github.com/user-attachments/assets/a7a6ee8b-3e6a-4991-80a8-8f0a7ef86393)

之前修过，issue #81 和 pr #87，好像还是有问题，可以初始化`this.valid`值为`false`https://github.com/gaogaotiantian/biliscope/blob/779a78cfb9bbebf6be16121a6f7548f23e1c16d1/scripts/ui.js#L290

以及后面设置完`display`后，把`this.valid`重置为`false`
https://github.com/gaogaotiantian/biliscope/blob/779a78cfb9bbebf6be16121a6f7548f23e1c16d1/scripts/ui.js#L718

**Comment by F-park** [comment]
不需要这么复杂，直接在 disable 函数里加一行 `this.valid = false;` 就好了。
因为视频卡片就是这么写的，不知道为啥用户卡片没有。

**Comment by noonisy** [comment]
> 不需要这么复杂，直接在 disable 函数里加一行 `this.valid = false;` 就好了。 因为视频卡片就是这么写的，不知道为啥用户卡片没有。

对的，没看视频卡片😂
