### ISSUE TITLE
不显示ai总结按钮

### ISSUE THREAD

**Issue by BardLyf** [gaogaotiantian/biliscope#262]
我的电脑firefox和edge没装bili scope都有ai总结按钮。chrome浏览器装了bili scope还是没有ai总结按钮。
![Snipaste_2024-11-14_20-07-39](https://github.com/user-attachments/assets/049b4026-2197-4d04-b0bc-c8c93e766ec5)

**Comment by BardLyf** [comment]
悬停总结可用
![Uploading Snipaste_2024-11-14_20-40-22.png…]()

**Comment by gaogaotiantian** [comment]
AI总结按钮不是biliscope加的，它和biliscope完全没有任何关系，是B站在灰度测试的一个功能。biliscope只是调用了后端的API去拿到这个信息。是不是在你的某个浏览器上显示这个按钮是完全由B站决定的。
