### ISSUE TITLE
关注列表里某些UP主信息显示失败

### ISSUE THREAD

**Issue by rochero** [gaogaotiantian/biliscope#27]
在**关注列表**中，对于某些 UP 主（比如[游民星空](https://space.bilibili.com/11233223)）插件无法显示信息，接口返回 401。但是我在搜索结果中试了试发现同样的接口却能够正常使用。

**Comment by rochero** [comment]
发现类似 issue #3

**Comment by gaogaotiantian** [comment]
这应该是因为短时间内大量的api call给block了……因为视频信息是一页一页读取的，如果数量太多可能就会让后台屏蔽掉。
