### ISSUE TITLE
显示最近更新时间和更新频率

### ISSUE THREAD

**Issue by Duyan013** [gaogaotiantian/biliscope#28]
通过获取的最近50视频数据中created时间戳(秒数)，计算平均更新间隔
尝试阅读过源码，有一点编程基础

**Comment by Duyan013** [comment]
![image](https://user-images.githubusercontent.com/105432844/235350909-25df2bb6-3b50-42a3-9e54-e73f095d93a8.png)
这里出现这个问题，导致不能加载词云，不知道是我改动了什么，但更新频率和上次更新时间已经正常显示了。

**Comment by Duyan013** [comment]
![image](https://user-images.githubusercontent.com/105432844/235351336-e3d766a1-85a0-4775-b9d4-91ace09e5b8e.png)
暂时看上去没有什么问题，虽然测试的还比较少。

**Comment by gaogaotiantian** [comment]
想法是不错的，没必要读最近50条，频率的部分读最近一个月就可以了。我打算直接实现了~

**Comment by gaogaotiantian** [comment]
最新的版本中已经完成
