### ISSUE TITLE
词云图上存在一些没用的关键词

### ISSUE THREAD

**Issue by This-is-ITC** [gaogaotiantian/biliscope#29]
例如有些up喜欢求三连，词云图上就会出现这种情况：
![image](https://user-images.githubusercontent.com/122453612/235599161-3247f7aa-b0aa-44de-959b-bf80eedfe3b7.png)
希望能屏蔽掉这些词

**Comment by gaogaotiantian** [comment]
这个用stopword也不一定管用，因为点和赞被分开了。但是可以像处理网址一样在raw string里把它给replace掉。是可以考虑的feature。

**Comment by gaogaotiantian** [comment]
Fixed.
