### ISSUE TITLE
更新0.3.0后出现了展示框越界

### ISSUE THREAD

**Issue by forchannot** [gaogaotiantian/biliscope#31]
![image](https://user-images.githubusercontent.com/100580891/236115126-bba6da19-8c57-447f-91a4-3d4544065b3d.png)
如图所示，在一些比较靠上的地方，不单单局限于动态这个页面，展示时并没有自适应往下，多次重试发现开始一瞬间是往下的，随后生成词云过后向上，造成越界导致无法看。
拓展为从git下载的
![image](https://user-images.githubusercontent.com/100580891/236115202-a2beccf1-861c-4275-bf3c-96d10abba008.png)

**Comment by gaogaotiantian** [comment]
这个应该是因为你屏幕的纵向分辨率相对有点小，导致上面下面都放不下，就随便放了……是不是只要你把屏幕往上或者往下滚一下就不出现这个问题了？

**Comment by forchannot** [comment]
我尝试缩小浏览器缩放比例确实可以，我的屏幕是常规笔记本的15.6英寸，浏览器正常缩放100的时候就会这样，因为是动态这个页面，无法向上或者向下滚动，在其他地方也需要滚动到特别严苛的位置才行
![image](https://user-images.githubusercontent.com/100580891/236116436-0919de9c-f8b9-45db-8ffb-bbb1438cb41f.png)
![image](https://user-images.githubusercontent.com/100580891/236116470-4188d158-c7ef-4e08-8539-c6419676e79c.png)

**Comment by gaogaotiantian** [comment]
这确实是个问题，我加个逻辑让它上下都不够的时候放中间。我平时测试用的27寸的显示器所以没意识到这个问题。

**Comment by gaogaotiantian** [comment]
这个问题其实一直有，只是3.0又加入了一些信息，可能框更大了……

**Comment by gaogaotiantian** [comment]
0.3.1修复了，得等Chrome那边审批过0.3.0才能发布。

**Comment by gaogaotiantian** [comment]
0.3.1已经通过审核了。
