### ISSUE TITLE
字词组合优化

### ISSUE THREAD

**Issue by PC314159** [gaogaotiantian/biliscope#32]
词云有时候会把一个词砍成分开来的几个字
![image](https://user-images.githubusercontent.com/132550970/236140538-feb4e0e0-751b-44f1-aa28-d582e23f9859.png)
比如
B站砍成  B   站
开源砍成 开   源
![image](https://user-images.githubusercontent.com/132550970/236141095-f6b6beee-f492-444a-9ca6-daed837ce5e6.png)

**Comment by gaogaotiantian** [comment]
这个事情目前没办法解决，是浏览器分词的问题。
