### ISSUE TITLE
userinfo api from Bilibili space didn't work as expected

### ISSUE THREAD

**Issue by noahlias** [gaogaotiantian/biliscope#33]
Reproduce:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/3949397/236397499-0bc6a7ca-c407-4f86-8efc-8a10be886de3.png">

部分用户的panel会查不出来数据 ,比如用户id (**2132180406**) 查看请求发现 
http://api.bilibili.com/x/space/wbi/acc/info?mid=2132180406 
通过浏览器访问api是没有问题的，返回结果正常，通过`fetch`获取数据异常
```json
{"code":-401,"message":"非法访问","ttl":1,"data":{"ga_data":{"decisions":["verify_captcha_level2"],"risk_level":1,"grisk_id":"92db46a0ba2f45d2395bc2755ee8d234","decision_ctx":{"buvid":"","decision_type":"4","ip":"x.x.x.x","mid":"0","scene":"anti_crawler","ua":"undici","v_checkIds":"","v_seconds":"120","v_times":"100","v_voucher":"voucher_2d1d8c6a-19e4-4257-9efe-2e908cb48337"}}}}
```

猜测是请求头ua和cookie的问题 经`过mitmproxy`抓包,  cookie中只需要个key, `buvid3` 等于任意值

<img width="711" alt="image" src="https://user-images.githubusercontent.com/3949397/236403654-4015246b-421e-4693-8e6e-809b3aabbaca.png">

**Comment by noahlias** [comment]
I found another question:
fetch data is working with nodejs but not working  as expected in the browser .
<img width="903" alt="image" src="https://user-images.githubusercontent.com/3949397/236432631-2de8c8bc-0b9a-444a-82f5-3349f355e3a3.png">

```js
var myHeaders = new Headers();
myHeaders.append(
  "User-Agent",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68"
);
myHeaders.append("Cookie", "buvid3=321321312");

var requestOptions = {
  method: "GET",
  headers: myHeaders,
  redirect: "follow",
};

fetch(
  "https://api.bilibili.com/x/space/wbi/acc/info?mid=2132180406",
  requestOptions
)
  .then((response) => response.text())
  .then((result) => console.log(result))
  .catch((error) => console.log("error", error));
```

**Comment by noahlias** [comment]
oh, I got the answer from [stackoverflow](https://stackoverflow.com/questions/45591594/fetch-does-not-send-headers) ,
add the `credentials: 'include'  `, and it make sense . no need to add header and cookie.
<img width="441" alt="image" src="https://user-images.githubusercontent.com/3949397/236436053-0d67d983-8c58-48a9-9c66-0c17c71b4ad1.png">

just change one line code and it works.
```js
            fetch(`${BILIBILI_API_URL}/x/space/wbi/acc/info?mid=${userId}`,{credentials: "include"})
```

**Comment by gaogaotiantian** [comment]
这个大概率是爬得频率太高被block了一小下，和credential没关系。你后面又work了是因为block的时间过去了……如果和credential有关，那这个API肯定所有的情况下没有credential都有问题。

**Comment by noahlias** [comment]
哈哈哈哈 好玄学， 就我刚点开的一个打不开
