### ISSUE TITLE
支持Firefox

### ISSUE THREAD

**Issue by FFDVDGD** [gaogaotiantian/biliscope#34]
请问会考虑对Firefox的支持吗？

**Comment by gaogaotiantian** [comment]
Dup #13 . Firefox最核心的问题在于，不支持`Intl.Segmenter()`，就没法在浏览器分词。

**Comment by silverling** [comment]
> Firefox最核心的问题在于，不支持`Intl.Segmenter()`，就没法在浏览器分词。

Firefox 在版本 125 后支持了这个 API，参考链接：
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter
https://www.mozilla.org/en-US/firefox/125.0.1/releasenotes/

UP 能否重新考虑一下支持 Firefox 😺

**Comment by silverling** [comment]
```diff
diff --git a/manifest.json b/manifest.json
index 743cbe0..38e989b 100644
--- a/manifest.json
+++ b/manifest.json
@@ -50,12 +50,18 @@
     "open_in_tab": false
   },
   "background": {
-    "service_worker": "changelog/background.js"
+    "scripts": ["changelog/background.js"]
   },
   "web_accessible_resources": [
     {
       "resources": ["img/bililv.svg", "scripts/sitescripts/*.js", "changelog/changelog.*"],
       "matches": ["https://*.bilibili.com/*"]
     }
-  ]
+  ],
+  "browser_specific_settings": {
+    "gecko": {
+      "id": "gaogaotiantian@hotmail.com",
+      "strict_min_version": "125.0"
+    }
+  }
 }
```

临时修改 `manifest.json` 并打包为 zip 文件，关闭 Firefox 插件签名认证（`xpinstall.signatures.required = false`)，可以成功加载插件，除了 **首页换一换前进后退** 功能，其他功能正常。先暂时这么用着了，期待 UP 的更新。

**Comment by gaogaotiantian** [comment]
我会关注一下firefox这边的情况，biliscope最近的用户数量确实变多了，所以会开始考虑firefox的support
