### ISSUE TITLE
分词优化建议：去掉日期

### ISSUE THREAD

**Issue by UniMars** [gaogaotiantian/biliscope#37]
是不是可以把日期模式的短语从分词的文本里先拿掉？
![image](https://github.com/gaogaotiantian/biliscope/assets/65664032/6615a90b-5d1b-4595-a848-e9101882dd68)

**Comment by gaogaotiantian** [comment]
确实是一个可以考虑的需求，但是事实上现在的词云是表达出了有效信息的——这个up会发各种每个月的评测之类的，这其实是一个有价值信息。

**Comment by UniMars** [comment]
有道理，不过对于纯数字的日期，比如2022/12/1 2022-12-1这种是不是可以考虑下

**Comment by gaogaotiantian** [comment]
> 有道理，不过对于纯数字的日期，比如2022/12/1 2022-12-1这种是不是可以考虑下

是的，这种确实应该提前过滤掉。

**Comment by gaogaotiantian** [comment]
Fixed in #66
