### ISSUE TITLE
请问本地保存的备注的具体路径是啥, 想做个软链接直接把本体存入云盘进行同步

### ISSUE THREAD

**Issue by XMB-7** [gaogaotiantian/biliscope#39]
如题, 这样也省得手动进行导入导出了.
另外请问这个本地数据是跟账号关联的么, 如果所有登录账号都能共享同一本地备注文件, 就很棒了.

**Comment by gaogaotiantian** [comment]
浏览器是不可以在不经用户允许的情况下偷偷在硬盘的确定路径下保存信息的。插件用的是chrome的保存机制，没法从硬盘上直接找到。这个数据应该是和浏览器绑定的，也就是你B站的所有账号应该是共享这个备注的。

**Comment by XMB-7** [comment]
了解了, 感谢回复, 大佬可以关闭该issue了, 或者留着提示其它用户也行.

**Comment by XMB-7** [comment]
忽然想到, 能否添加一个周期性自动导出备份的功能, 比如设置一个选项, 开启后, 每天/周/月会自动弹出一个引导用户确认进行备份导出的对话框.

**Comment by gaogaotiantian** [comment]
没事就弹框也是个挺让人头疼的事情吧。。而且弹框本身可能也是需要一些额外的权限。。

**Comment by XMB-7** [comment]
如果好实现的话, 可能还是有需求的. 比如每月弹框一次, 频率应该可以接受. 
另外就是用户可以选择是否开启这一功能, 不需要的直接禁用相关设置选项即可.

**Comment by F-park** [comment]
### 本地保存备注的具体路径

> 扩展 ID 可以在 `chrome://extensions/` 里点插件详细信息找到
> 如果你在浏览器使用了多用户，那下面路径的 `Default` 是要改成其他名字的。

Edge的本地扩展数据位置
%LOCALAPPDATA%\Microsoft\Edge\User Data\Default\Local Extension Settings\你的 `biliscope` 扩展 ID

Chrome的本地扩展数据位置
%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\你的 `biliscope` 扩展 ID

### 周期性自动导出备份

我觉得完全没必要做这个功能，直接做两个按钮`上传本地标签云端`和`从云端下载标签`就好了。

**Comment by XMB-7** [comment]
@F-park 感谢, 学到了. 已尝试把biliscope本地数据用软链接放进云盘, 暂时没发现有什么问题. 看来所有浏览器插件都能这么处理, 再也不用想着备份了.
