### ISSUE TITLE
在“个人中心”页面，鼠标划至“个人空间”标签时，弹出的窗口内容异常

### ISSUE THREAD

**Issue by NekoisJelly** [gaogaotiantian/biliscope#4]
-步骤：
进入B站，在个人头像弹出的窗口中进入“个人中心”
下滑找到左侧的“个人空间”标签，鼠标移动上去，弹出窗口

-环境：
win11+edge（版本 110.0.1587.63）

-特殊提示：
edge浏览器安装的chrome商店的插件=。=

截图：
![image](https://user-images.githubusercontent.com/8220455/224466263-23a120ac-09b3-4209-8cc3-06786d2130ae.png)

**Comment by gaogaotiantian** [comment]
你鼠标放到这个个人空间上的时候，浏览器左下角有显示这个link是什么么？

**Comment by NekoisJelly** [comment]
显示的链接是：space.bilibili.com，似乎已经fix啦？我刚才看了看已经不弹了~

**Comment by gaogaotiantian** [comment]
理论上说单纯的space.bilibili.com不应该触发这个窗口……

**Comment by gaogaotiantian** [comment]
如果你还能复现的话，再reopen这个issue好了，我这边是没法复现这个问题~
