### ISSUE TITLE
[FR] 在浮窗上直接添加备注, 不知有无可能实现

### ISSUE THREAD

**Issue by XMB-7** [gaogaotiantian/biliscope#40]
感谢大佬给B站完善功能. 如果能在任意页面的浮窗上直接键入备注, 而不必进入up个人空间, 那就更美妙了.
设想比如按住ctrl等键使浮窗变得固定, 能将鼠标移动到备注显示的区域, 点击触发弹出备注输入栏之类的.

**Comment by gaogaotiantian** [comment]
理论上这确实更好，但是对现在的代码框架改动也会比较大。未来如果用户数量多了，同时这个需求变大了，可能会考虑做。目前来说的话需要的时间比较多。

**Comment by Dynesshely** [comment]
赞成 @XMB-7 提出的按住 ctrl 使浮窗固定的想法, 这样也许可以让卡片上的内容可点击

**Comment by gaogaotiantian** [comment]
在 #51 实现了这个功能。
