### ISSUE TITLE
[FR] 从引入备注扩展到引入标签

### ISSUE THREAD

**Issue by XMB-7** [gaogaotiantian/biliscope#41]
比如类似zotero的文件夹和标签的双重组织管理架构. 目前B站只有分组(类比于文件夹), 但没有标签(不同up可以拥有同一标签, 同一up可以拥有不同标签). 不知可否从引入备注拓展到引入标签, 甚至再继而拓展到针对标签进行过滤搜索等高阶功能.

虽然这一功能请求已然超出了该插件的本意, 但倘若真能实现的话, 对b站的功能增强将是极其巨大的. 另如果再能扩展到对已收藏的视频的分类组织管理, 那真的就是再好不过了. 

ps. 感谢大佬无私奉献. 顺便也吐槽下, 真是天下苦b站久矣, 功能开发个半截就不管了, 等官方提高视频笔记的使用体验都等了好久了...

**Comment by gaogaotiantian** [comment]
标签本身的引入其实不那么难，但是针对标签搜索就需要专门的UI适配了，就有点超出这个插件本身的功能范畴了。

**Comment by XMB-7** [comment]
> 但是针对标签搜索就需要专门的UI适配了，就有点超出这个插件本身的功能范畴了。

确实, 但标签(及其检索)作为备注的延展, 也真的挺有用的, 还是希望日后能有机会将之纳入插件的功能中.

**Comment by gaogaotiantian** [comment]
这周末抽出一点时间把标签系统完成了。
