### ISSUE TITLE
拉黑或被拉黑会导致在个人主页无法查看备注，以及希望提升150字的字数限制

### ISSUE THREAD

**Issue by XDcedar** [gaogaotiantian/biliscope#45]
~~不要问我怎么知道的~~

主要是因为被拉黑和拉黑对方后，就定位不到个人主页上的“个人资料”了。也许可以直接 `appendChild` 到 `col-2` 的位置？

**Comment by gaogaotiantian** [comment]
都被拉黑了，就不需要备注了吧！

**Comment by XDcedar** [comment]
需要的，可以备注一下为啥拉黑他，或者为啥被他拉黑了，还可以标一下拉黑或被拉黑的时间什么的
而且有时候是先写好备注了，后来才拉黑或者被拉黑的

**Comment by gaogaotiantian** [comment]
想了一下好像确实是这样，我最近看一下这个怎么修改合适~

**Comment by XDcedar** [comment]
其实还挺好改的，两行就能改好，天哥看一下
``` javascript
const sideColumnNode = document.querySelector("div.col-2");
// 想增加一点稳定性就这么写，虽然我感觉应该没必要，反正只要B站想改那怎么写都会失效（
// const sideColumnNode = document.querySelector(".section.user-info")?.parent || document.querySelector("div.col-2");
sideColumnNode.appendChild(noteNode);
```

参考：[Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) 和 [querySelector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector)

另外希望能顺手把文本框的字数限制去掉或者改大一些（比如5万字），保存在本地就不要设置得那么小了吧😂 文字而已不占地方的，而且大部分备注也写不了多少（主要是我会备注我关注的UP主的入坑视频和喜欢的视频，一个视频链接就能占50字，150字只够我贴几个视频链接..）

**Comment by gaogaotiantian** [comment]
`div.col-2`还是有点太广了，不是失效的问题，是未来存在影响其他地方的可能性。失效相对来说是一个更可接受的behavior。

本地的大小也是有限制的，不是你硬盘多大就有多大的（当然这个可以request）。更本质的问题不是能存多少，是这个备注会显示在card上啊，你备注了5万字你card咋显示？

**Comment by gaogaotiantian** [comment]
我可以加一个简单的语法去给你额外的空间写只有网页上看得到的备注……

**Comment by XDcedar** [comment]
侧边栏应该就是拿来摆各种卡片的吧，我觉得将来也不会再在这个侧边栏里多包一层的，如果担心的话，就用注释里那个写法？反正拉黑后，侧边栏就是空的了，也就没别的地方可以插入了，检索 `div.col-2` 也就不要紧了

高度的话，可以把 `textarea` 用 CSS 改成可调大小的呀。我刚刚搜索了一下，CSS 加上 `resize: vertical;` 就能做到拖拽右下角改变高度了，挺方便的。

**Comment by gaogaotiantian** [comment]
你不能保证整个页面只有一个`div.col-2`。有可能未来有其他的地方（前面的header下面的footer之类）出现`div.col-2`，这是个非常非常常见的bootstrap class，所以直接在document上去query `col-2`是不合适的。

不是你侧边栏显示的问题，是备注会出现在user profile card上，这是备注的核心功能。。

![image](https://github.com/gaogaotiantian/biliscope/assets/13121107/b504af3d-a594-428f-bacf-8d6e35bd0caa)

这里要显示备注的，你写五万字你这个卡怎么放得下

**Comment by XDcedar** [comment]
> 你不能保证整个页面只有一个`div.col-2`。有可能未来有其他的地方（前面的header下面的footer之类）出现`div.col-2`，这是个非常非常常见的bootstrap class，所以直接在document上去query `col-2`是不合适的。

啊，有道理，我观察了一下，可以这样改：`document.querySelector("#page-index > div.col-2");` 它的页面里，`page-index` 是 id，肯定不会重复的。

> 这里要显示备注的，你写五万字你这个卡怎么放得下

喔，这里确实不记得了。不过改起来也简单，备注那里限制高度，超字数就改用省略号 `text-overflow: ellipsis;` 这样就行了
一般来说也不会顶着上限写的啦，上限是五万字但绝大部分备注最后也就几百字而已..只不过字数限制放宽一些，写起来会更自由，不然缩句真的痛苦

> 本地的大小也是有限制的，不是你硬盘多大就有多大的（当然这个可以request）。

本地大小我觉得对文字来说真的可以算作无限了，5MB能写174w字了，实在不行就申请 unlimitedStorage 吧

**Comment by gaogaotiantian** [comment]
在 #46 解决了这两个问题，黑名单里的人也显示备注了。单个up的文字限制扩充到了5000，在卡片上只显示备注第一行的内容，也就是你可以决定备注上看到什么内容，然后剩下的东西只有在主页才能看到。你可以review下code，我估计明天merge。
