### ISSUE TITLE
在使用Bili-Evolved的自定义顶栏后，卡片没有在最顶层展示

### ISSUE THREAD

**Issue by forchannot** [gaogaotiantian/biliscope#47]
这是插件的链接[Bili-Evolved](https://github.com/the1812/Bilibili-Evolved/blob/master/registry/dist/components/style/custom-navbar.js)
使用之后效果如下图所示
![image](https://github.com/gaogaotiantian/biliscope/assets/100580891/8917a391-34c2-475f-aa11-e2c30968f6dd)
展示卡片被动态卡片遮盖了，是否可以调整下展示卡片的堆叠顺序让他展示在最上层

**Comment by gaogaotiantian** [comment]
这个插件本身希望自己在“最上面”，它明显盖住了B站不少的内容。我们的z-index已经设置的不小，但是对于一个希望自己在“最上面”的插件，和它竞争最上面是没啥意义的。你是在鼠标放到哪儿的时候弹出的biliscope的card？是B站的内容还是这个插件显示的内容？

**Comment by forchannot** [comment]
如上个评论图那样，鼠标放在了央视新闻up主那里，biliscope显示的卡片被另一个插件提供的动态卡片所遮挡了，可以在图上看到右半部分有biliscope的卡片

**Comment by gaogaotiantian** [comment]
你的鼠标放到的是那个动态卡片上面的一个链接么？

**Comment by forchannot** [comment]
![image](https://github.com/gaogaotiantian/biliscope/assets/100580891/b48a5b4e-b222-48b8-8857-486c794c403e)
我重新截了张图，这次没有隐藏鼠标指针了

**Comment by gaogaotiantian** [comment]
ok，这个问题我可能可以解决，我先下一个这个插件。

**Comment by gaogaotiantian** [comment]
你用的什么组件？

**Comment by forchannot** [comment]
![image](https://github.com/gaogaotiantian/biliscope/assets/100580891/27c05f4d-39b6-4713-88ee-1846428bb6fd)
天哥我自己试了下，将biliscope的z-index改为10002后即可刚好在他的上层显示

**Comment by gaogaotiantian** [comment]
这不是一个有价值的改动，它以后要变10003了呢？

**Comment by gaogaotiantian** [comment]
ok修复了这个问题了，现在它会找target底下的zindex了。但是这个fix需要等下一个release才能用到，除非你直接从github source拉代码~

**Comment by forchannot** [comment]
好的，感谢天哥
