### ISSUE TITLE
在热门页面下晃动鼠标有概率导致卡片不消失

### ISSUE THREAD

**Issue by yxyh357** [gaogaotiantian/biliscope#5]
![QQ录屏20230311135134](https://user-images.githubusercontent.com/101318611/224467867-12566989-5db5-4aba-a776-0d86e431a48c.gif)

**Comment by yxyh357** [comment]
![QQ录屏20230311135134](https://user-images.githubusercontent.com/101318611/224467867-12566989-5db5-4aba-a776-0d86e431a48c.gif)

**Comment by gaogaotiantian** [comment]
这里的sync确实做的有点粗糙。我看看能不能解决。

**Comment by gaogaotiantian** [comment]
在 https://github.com/gaogaotiantian/biliscope/commit/0743628134947e01441df15fcaf3a74e7bf88d59 修复了
