### ISSUE TITLE
在悬浮卡片上直接添加中文备注, 卡片有时会概率性地消失, 致使添加失败. 

### ISSUE THREAD

**Issue by XMB-7** [gaogaotiantian/biliscope#53]
环境: win11 edge
准备添加中文备注"啊啊啊", 但当打到第三个a时, 悬浮卡片自动关闭, 备注直接添加失败.
无法稳定复现, 有时添加好使, 有时不好使, 暂时没发现触发的规律. 但在英文输入法下, 输入英文备注, 始终未遇到这一个问题.
另外应该跟具体的输入法无关, 测试微软输入法搜狗输入法讯飞输入法都有该问题.
![msedge_C2EJEhE2mN](https://github.com/gaogaotiantian/biliscope/assets/65625632/9ca21e77-0e7a-48f5-be5d-7d92120ff64d)

**Comment by gaogaotiantian** [comment]
是bug，会尽快解决~

**Comment by gaogaotiantian** [comment]
这里的直接原因是鼠标进入输入法的那个框框了，然后浏览器认为它“离开”了卡片。

但是我思考了一下，我觉得在用户输入备注的时候，哪怕是鼠标真的离开了卡片，也不应该直接把卡片弄没，因为用户的数据依然可能丢失。所以现在改了一下设计，如果用户处于输入状态，卡片会固定在屏幕上，哪怕鼠标离开也不会消失。只有在用户结束输入（通过点击卡片内部或者外部）的时候，卡片才会消失，并且会保存用户的输入。

**Comment by gaogaotiantian** [comment]
另外这是对用户影响比较大的一个bug，正好v0.4.0也没宣传呢，我就直接更版本到0.4.1了。

**Comment by XMB-7** [comment]
感谢大佬
