### ISSUE TITLE
用户浮窗内无法点击跳转

### ISSUE THREAD

**Issue by JrDw0** [gaogaotiantian/biliscope#56]
![动画](https://github.com/gaogaotiantian/biliscope/assets/37445725/55453457-acac-4984-9c67-63bcb66e4309)
用户浮窗里的关注、粉丝、标签都没法超链接本来就是这样的嘛，希望能和原版的一样可以超链

**Comment by JrDw0** [comment]
gif里少打了一个#，但是打了也加不上自定义标签

**Comment by gaogaotiantian** [comment]
确实就是这么设计的，主要是考虑到好像没有什么去点“关注”和“粉丝”的需求吧，你平时点进去主要是为了看什么呢？

标签原版就是没有的东西，是我加上的。这几个分区标签倒是可以link到分区，也是觉得好像意义不大，不是不能加。现在是自己加的标签有link。

**Comment by gaogaotiantian** [comment]
说时迟那时快，#58 已经增加了分区的link功能。

**Comment by gaogaotiantian** [comment]
关注和粉丝也已经加进去了，这个issue我就close了~
