### ISSUE TITLE
feature：建议增加关注和取消关注功能

### ISSUE THREAD

**Issue by Flow-sandyu** [gaogaotiantian/biliscope#57]
目前的情况是显示界面里不能关注和取消关注，要点进个人空间才能进行关注和取消关注
![image](https://github.com/gaogaotiantian/biliscope/assets/72751523/a624cc75-0a16-4f1c-92a0-10c5abb24ecb)

而原本B站的功能，是支持在显示界面里关注和取消关注用户的，比如
![image](https://github.com/gaogaotiantian/biliscope/assets/72751523/b1164c47-f06b-456c-be6d-c51f2aa1e431)
![image](https://github.com/gaogaotiantian/biliscope/assets/72751523/815240d9-8ab0-42cc-aa64-08b424cf3299)

对我来说，关注和取消关注是一个高频使用的功能，这也是我提issue的原因

**Comment by gaogaotiantian** [comment]
我会研究一下这个，我也觉得关注其实是个有意义的功能。

**Comment by gaogaotiantian** [comment]
在 #59 中增加了这个功能。下一个release就会放出。
