### ISSUE TITLE
疑似没有排除视频简介下链接的信息

### ISSUE THREAD

**Issue by yxyh357** [gaogaotiantian/biliscope#6]
![屏幕截图(73)](https://user-images.githubusercontent.com/101318611/224468559-29f2eb98-8da7-438f-974a-84ebeb000e52.png)
![屏幕截图(74)](https://user-images.githubusercontent.com/101318611/224468564-dff07815-6b5d-4df2-8e1c-058b4f0ac42e.png)

**Comment by gaogaotiantian** [comment]
视频简介下链接的信息确实没有排除，有的人在自己的视频简介里会写一个链接，目前这算是by design吧。

**Comment by UniMars** [comment]
> 

是不是可以用正则屏蔽连接？

**Comment by gaogaotiantian** [comment]
技术上当然不是不行，我得稍微想一下要不要这么干。

**Comment by gaogaotiantian** [comment]
在[c6042d](https://github.com/gaogaotiantian/biliscope/commit/c6042d08fdc65c8f82d9a4298137ea99dc4f12b7)中解决了这个问题。
