### ISSUE TITLE
鼠标悬浮在番剧动画类的视频动态的名称（对应一般视频up主名称的位置）上面时，展示的是一个不知道是谁的详情

### ISSUE THREAD

**Issue by lammonx** [gaogaotiantian/biliscope#78]
1. 右上角-动态-视频动态

![image](https://github.com/gaogaotiantian/biliscope/assets/64029406/88310420-c674-4c24-b3d7-0154b5a9de83)

2.点击右上角动态-动态首页 

![image](https://github.com/gaogaotiantian/biliscope/assets/64029406/459e33bd-9050-4500-bfe5-db6291cd4686)

**Comment by gaogaotiantian** [comment]
这是B站的bug，你点一下对应的链接也是去到这个up的主页，并且他的主页签名是

> 估计是出BUG了，我和凡人修仙传没任何关系 /(ㄒoㄒ)/~~

和插件没关系~

**Comment by lammonx** [comment]
我感觉番剧动画类的得特殊处理一下，不能和正常up一样处理

**Comment by lammonx** [comment]
> 这是B站的bug，你点一下对应的链接也是去到这个up的主页，并且他的主页签名是
> 
> > 估计是出BUG了，我和凡人修仙传没任何关系 /(ㄒoㄒ)/~~
> 
> 和插件没关系~

我感觉番剧动画类的得特殊处理一下，不能和正常up一样处理

**Comment by gaogaotiantian** [comment]
就像我提到的，这是B站的bug，我看了一下，B站已经修复了，所以插件也不会错误显示了。如果你还有这个问题~可以reopen这个issue。
