### ISSUE TITLE
移动到已注销账号时会显示错误

### ISSUE THREAD

**Issue by muoshuosha** [gaogaotiantian/biliscope#81]
![}}@DXJ) O0G0E84 DC)7`0U](https://github.com/gaogaotiantian/biliscope/assets/54895915/98862288-54b0-432f-8c89-01e6f2886357)

如图所示，我先移动到`亿点点不一样`这个账号能正常显示，再移动到上面那个已注销的用户会显示上一次的结果

**Comment by gaogaotiantian** [comment]
确实是这样的。没有做专门的注销账户的处理。作为用户，你希望移到注销账户上的时候的结果是什么呢？

**Comment by muoshuosha** [comment]
> 确实是这样的。没有做专门的注销账户的处理。作为用户，你希望移到注销账户上的时候的结果是什么呢？

我期望移到注销用户上的结果至少得是固定的，而不是随着上一个移动到的用户的改变而改变

**Comment by dan-kuroto** [comment]
补充一下，如果一开始就移动到已注销账号的话，会显示这样的结果：
![image](https://github.com/gaogaotiantian/biliscope/assets/69581083/b19ef4c6-81a5-4970-8969-b338fc6dbe38)

另外，**对已注销账号添加的备注也会失效无法显示**。

希望对于已注销账号，头像、用户名和简介能和B站默认显示的内容相同，且仍能显示之前对该账号添加的备注（这样就能知道这个账号是谁了）。

另外如果可以，还希望能有个标签之类的，标注账号处于已注销状态（因为有些B站用户会故意改名叫 `账号已注销` ……😂）
