### ISSUE TITLE
无法对文件进行下载

### ISSUE THREAD

**Issue by PC-Killer** [gaogaotiantian/biliscope#82]
<img width="1280" alt="image" src="https://github.com/gaogaotiantian/biliscope/assets/132468459/37367a9f-f5c2-48ba-b550-1a42924fe200">
<img width="1280" alt="image" src="https://github.com/gaogaotiantian/biliscope/assets/132468459/c569bf26-7cf2-4673-88b3-f3159f96b2b3">
<img width="1280" alt="image" src="https://github.com/gaogaotiantian/biliscope/assets/132468459/c2c186a4-2a69-4a69-a83d-c7271d86bea7">

**Comment by gaogaotiantian** [comment]
这个肯定是你的网络问题，而且这个事情完全不是repo owner能控制的，这是github的infra。我刚才试了一下是可以下载的，所以我close了。
