### ISSUE TITLE
[FR] 添加选项, 允许选择是否将已关注up所属的分组名自动添加为标签

### ISSUE THREAD

**Issue by XMB-7** [gaogaotiantian/biliscope#86]
比如已关注up甲并将之添加到`体育`分组, 那么当用户在给up甲添加自定义标签的时候, 比如`#篮球#`, 那么也自动添加一个`#体育#`标签.
这样可以让用户把b站自带的up分组功能作为一级分类, 然后在其基础上添加自定义标签来作为二级分类, 这样用起来或许更方便. (要把分组标签自动添加到自定义标签之前)

**Comment by gaogaotiantian** [comment]
现在的标签是没有多级分类的啊，另外标签是完全text based的。一个可能的方式是在那个profile card上直接显示这个up的分组标签（不同于直接文字添加的标签），这个或许是可以做到的，用一个不同的颜色显示。

**Comment by XMB-7** [comment]
我的意思是指概念上的多级分类, 而不是想要创建多级分类标签. 
具体举个应用例子, 比如我在用油猴脚本`b站时间线筛选`按up分组情况来分组地查看up动态. 此时我对up的分组, 必然只能是一级分类, 我只可能把篮球up足球up台球up乒乓球up羽毛球up统一分进一个组, 组名起做`体育`, 而不可能给每个体育项目都创建一个分组. 而这个`体育`就是概念上的一级分类, 显然它不可能取名取得太具体.
而往下, 现在我的`体育`分组里, 有各种项目的up, 那我在给它们逐个写自定义标签的时候, 自然就想要写具体的项目来作为标签, 这就是概念上的二级分类, 比如`#篮球#` `#足球#`... 
但我同时又希望, 能自动把`#体育#`也作为标签写上, 以免我给每个组内up都手动地添加一个`#体育#`. 这样一来, 我在搜索up的时候, 就能用`#体育#`来搜索了. 否则有时我可能记不住自己到底写了然后应该搜索哪些标签, 比如到底是写了`#篮球#`, 还是`#男篮# #女篮#`, 此时我就可以选择去搜索`#体育#`.

**Comment by gaogaotiantian** [comment]
今天抽空把这个做了，#88。现在你在B站做的分组会以tag的形式展示在卡片上了。

![image](https://github.com/gaogaotiantian/biliscope/assets/13121107/e3b6e147-b9c1-456b-91e9-8f31fbd07d65)
