### ISSUE TITLE
[FR] 搜索标签时不需要用户手动跳转至用户搜索界面

### ISSUE THREAD

**Issue by F-park** [gaogaotiantian/biliscope#95]
### 新功能描述
现在搜索自定义标签的方式，需要经过两次页面跳转才能搜到自定义标签分组的用户（有点麻烦），而使用 `omnibox` 可以使用全键盘搜索而且直接进到用户搜索页面。（参考这个[项目](https://github.com/hanguokai/mdn-search)的图片）
浏览器有自带这一功能: `edge://settings/searchEngines?search=搜索引擎`，但不能自定义搜索框下面候选的内容，只能进行某一缺省链接的快捷访问。

### 新功能的操作方法
1.  `ctrl+l` 打开搜索栏
2. 输入`biliscope内置的快捷方式（可以简称bs）`，按下 `tab` 键进入快捷方式搜索
3. 输入想搜索的标签，按下 `enter` 键进入b站的用户搜索界面

### 新功能的一些细节想法
`自定义搜索框下面候选的内容`挺有创造性的，如果搜索的字符串前面为#就把搜索用户的结果优先级排到最高，其他的话就综合优先级最高（当然搜其他也可以用其他前缀，然后默认访问优先级最高的结果）

**Comment by gaogaotiantian** [comment]
我人生中没听说过这个功能。我想大部分的用户应该也是一样的。功能本身的使用要尽量贴近B站用户对B站的使用习惯，而不是使用一些浏览器的神奇功能……

当然，如果你想通过某些方法把中间那个跳转拿掉，我是欢迎的。

**Comment by F-park** [comment]
> 我人生中没听说过这个功能。我想大部分的用户应该也是一样的。功能本身的使用要尽量贴近B站用户对B站的使用习惯，而不是使用一些浏览器的神奇功能……
> 
> 当然，如果你想通过某些方法把中间那个跳转拿掉，我是欢迎的。

我的这个思路确实太过复杂了，需要一定门槛来习惯。不使用 `omnibox` 的话，还可以通过自动重定向（正常也不会搜索#或@开头的内容，搜这两种情况大概率也是搜用户的）来避免用户手动两次跳转，之前用过一个[插件](https://github.com/einaregilsson/Redirector)，就是实现类似功能的，但疑似需要新的权限，不知道这是否是可以接受的。
